// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// compute_stats
DataFrame compute_stats(std::vector<double> observed, std::vector<double> predicted);
RcppExport SEXP rEDM_compute_stats(SEXP observedSEXP, SEXP predictedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type predicted(predictedSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_stats(observed, predicted));
    return rcpp_result_gen;
END_RCPP
}
