// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// compute_stats
DataFrame compute_stats(NumericVector observed, NumericVector predicted);
RcppExport SEXP rEDM_compute_stats(SEXP observedSEXP, SEXP predictedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type observed(observedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type predicted(predictedSEXP);
    __result = Rcpp::wrap(compute_stats(observed, predicted));
    return __result;
END_RCPP
}
